version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: performance_app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:cached
      - ./frontend:/app/frontend:cached
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run start

volumes:
  node_modules:
