version: "3.9"

services:
  app:
    build: .
    container_name: performance_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm start
